baseurl = "your-base-url"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = ""
title = "Cocoa-EH"
pygmentsuseclasses = true
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = ""
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = ""
logofile = "images/logo.png"
faviconfile = "images/logo.png"
highlightjs = true
lang = "en"
github = ""
email = ""
linkedin = ""
twitter = ""